package:
    name: cam_record_server
    version: 0.0.1

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - cam_server

build:
  entry_points:
    - cam_record_server = cam_record_server.start_cam_record_server:main

about:
    home: https://www.github.com/paulscherrerinstitute/cam_record_server
